USE `essentialmode`;

INSERT INTO `items` (name, label) VALUES 
	('bread', 'Pain'),
	('water', 'Eau'),
	('twix', 'Twix'),
	('snickers', 'Snickers'),
	('mars', 'Mars'),
	('bounty', 'Bounty'),
	('kitkat', 'Kit-Kat'),
	('chips', 'Chips'),
	('fanta', 'Fanta'),
	('candy', 'Bonbon'),
	('cookie', 'Cookie'),
	('granola', 'Granola'),
	('sandwich', 'Sandwich'),
	('beer', 'Biere'),
	('panache', 'Panaché'),
	('sangria', 'Sangria'),
	('nouille', 'Yum-Yum'),
	('chocolatnoir', 'Chocolat Noir'),
	('chocolatblanc', 'Chocolat Blanc'),
	('limonade', 'Limonade'),
	('apple', 'Pomme'),
	('banana', 'Banane'),
	('poire', 'Poire'),
	('kiwi', 'Kiwi'),
	('fraise', 'Fraise'),
	('framboise', 'Framboise'),
	('porto', 'Porto'),
	('sumol', 'Sumol'),
	('miranda', 'Miranda'),
	('pepsi', 'Pepsi'),
	('pancake', 'Pancake'),
	('gaufre', 'Gaufre')
;
